# Generated by Django 4.2.7 on 2024-02-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_thing_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='../media/images'),
        ),
    ]
