# Generated by Django 4.2.7 on 2024-02-02 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_thing_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='feedback_id',
        ),
        migrations.AddField(
            model_name='feedback',
            name='trade_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.trade'),
        ),
    ]
