# Generated by Django 4.2.7 on 2024-02-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_country_thingimage_remove_location_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thingimage',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
