# Generated by Django 4.2.7 on 2024-02-09 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_thingimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user_side',
        ),
    ]
