
INSERT INTO main_category VALUES (1, 0, 'Товары');
INSERT INTO main_category VALUES (2, 0, 'Услуги');
INSERT INTO main_category VALUES (3, 1, 'Компьютеры');
INSERT INTO main_category VALUES (4, 1, 'Авто');
INSERT INTO main_category VALUES (5, 1, 'Телефоны');
INSERT INTO main_category VALUES (6, 1, 'Электроника и Фото');
INSERT INTO main_category VALUES (7, 1, 'Бытовая техника');
INSERT INTO main_category VALUES (8, 1, 'Все для офиса');
INSERT INTO main_category VALUES (9, 1, 'Аптека');
INSERT INTO main_category VALUES (10, 1, 'Все для дома');
INSERT INTO main_category VALUES (11, 1, 'Детский мир');
INSERT INTO main_category VALUES (12, 1, 'Досуг и развлечения');
INSERT INTO main_category VALUES (13, 1, 'Животные и растения');
INSERT INTO main_category VALUES (14, 1, 'Книги');
INSERT INTO main_category VALUES (15, 1, 'Красота и здоровье');
INSERT INTO main_category VALUES (16, 1, 'Музыка, видеофильмы');
INSERT INTO main_category VALUES (17, 1, 'Одежда, обувь и принадлежности ');
INSERT INTO main_category VALUES (18, 1, 'Подарки, сувениры, цветы ');
INSERT INTO main_category VALUES (19, 1, 'Продукты, напитки, табак');
INSERT INTO main_category VALUES (20, 1, 'Путешествия, туризм ');
INSERT INTO main_category VALUES (21, 1, 'Спортивные товары');
INSERT INTO main_category VALUES (22, 1, 'Строительство и ремонт');
INSERT INTO main_category VALUES (23, 1, 'Оборудование');
INSERT INTO main_category VALUES (24, 4, 'Аудиотехника');
INSERT INTO main_category VALUES (25, 4, 'Легковые автомобили');
INSERT INTO main_category VALUES (26, 4, 'Автокосметика');
INSERT INTO main_category VALUES (27, 4, 'Автозапчасти');
INSERT INTO main_category VALUES (28, 4, 'Сигнализация');
INSERT INTO main_category VALUES (29, 4, 'Аксессуары');
INSERT INTO main_category VALUES (30, 4, 'Автохимия');
INSERT INTO main_category VALUES (31, 4, 'Шины');
INSERT INTO main_category VALUES (32, 4, 'Мототехника');
INSERT INTO main_category VALUES (33, 4, 'Грузовые машины');
INSERT INTO main_category VALUES (34, 4, 'Спецтехника');
INSERT INTO main_category VALUES (35, 4, 'Инструменты');
INSERT INTO main_category VALUES (36, 4, 'Колесные диски');
INSERT INTO main_category VALUES (37, 4, 'Автомобильная видеотехника');
INSERT INTO main_category VALUES (38, 24, 'Магнитолы');
INSERT INTO main_category VALUES (39, 24, 'Антенны');
INSERT INTO main_category VALUES (40, 24, 'Усилители');
INSERT INTO main_category VALUES (41, 24, 'Автоакустика');
INSERT INTO main_category VALUES (42, 24, 'Аксессуары');
INSERT INTO main_category VALUES (43, 24, 'Чейнджеры');
INSERT INTO main_category VALUES (44, 26, 'Полироли');
INSERT INTO main_category VALUES (45, 26, 'Автошампуни');
INSERT INTO main_category VALUES (46, 26, 'Очистители');
INSERT INTO main_category VALUES (47, 26, 'Автоэмали');
INSERT INTO main_category VALUES (48, 26, 'Шпаклевка');
INSERT INTO main_category VALUES (49, 26, 'Грунтовка');
INSERT INTO main_category VALUES (50, 27, 'Аккумуляторные батареи');
INSERT INTO main_category VALUES (51, 27, 'Двигатель');
INSERT INTO main_category VALUES (52, 27, 'Кузов');
INSERT INTO main_category VALUES (53, 27, 'Рулевое управление');
INSERT INTO main_category VALUES (54, 27, 'Электрика');
INSERT INTO main_category VALUES (55, 27, 'Масляные фильтры');
INSERT INTO main_category VALUES (56, 27, 'Топливная система');
INSERT INTO main_category VALUES (57, 27, 'Шасси');
INSERT INTO main_category VALUES (58, 27, 'Топливные фильтры');
INSERT INTO main_category VALUES (59, 27, 'Система выпуска');
INSERT INTO main_category VALUES (60, 27, 'Подвеска');
INSERT INTO main_category VALUES (61, 27, 'Трансмиссия');
INSERT INTO main_category VALUES (62, 27, 'Фары');
INSERT INTO main_category VALUES (63, 27, 'Тормозная система');
INSERT INTO main_category VALUES (64, 28, 'Механические блокираторы');
INSERT INTO main_category VALUES (65, 28, 'Автопейджеры');
INSERT INTO main_category VALUES (66, 28, 'Автосигнализации');
INSERT INTO main_category VALUES (67, 28, 'Иммобилайзеры');
INSERT INTO main_category VALUES (68, 29, 'Антирадары');
INSERT INTO main_category VALUES (69, 29, 'Насосы');
INSERT INTO main_category VALUES (70, 29, 'Зеркала заднего вида');
INSERT INTO main_category VALUES (71, 29, 'Автоаптечки ');
INSERT INTO main_category VALUES (72, 29, 'Парковочные радары');
INSERT INTO main_category VALUES (73, 29, 'Щетки, дворники');
INSERT INTO main_category VALUES (74, 29, 'Резиновые коврики');
INSERT INTO main_category VALUES (75, 29, 'Багажники');
INSERT INTO main_category VALUES (76, 29, 'Освежители воздуха');
INSERT INTO main_category VALUES (77, 29, 'Пылесосы');
INSERT INTO main_category VALUES (78, 29, 'Сигналы');
INSERT INTO main_category VALUES (79, 29, 'Тюнинг комплекты');
INSERT INTO main_category VALUES (80, 29, 'Акустические полки, короба и подиумы');
INSERT INTO main_category VALUES (81, 29, 'Подсветка');
INSERT INTO main_category VALUES (82, 29, 'Внешний декор');
INSERT INTO main_category VALUES (83, 29, 'Автомобильные холодильники');
INSERT INTO main_category VALUES (84, 29, 'Рули');
INSERT INTO main_category VALUES (85, 29, 'Ручки КПП');
INSERT INTO main_category VALUES (86, 29, 'Спортивные сиденья');
INSERT INTO main_category VALUES (87, 29, 'Ксенон');
INSERT INTO main_category VALUES (88, 30, 'Моторные масла');
INSERT INTO main_category VALUES (89, 30, 'Масло трансмиссионное');
INSERT INTO main_category VALUES (90, 30, 'Антифризы');
INSERT INTO main_category VALUES (91, 30, 'Присадки в масло');
INSERT INTO main_category VALUES (92, 30, 'Присадки в топливо');
INSERT INTO main_category VALUES (93, 30, 'Герметики');
INSERT INTO main_category VALUES (94, 30, 'Преобразователь ржавчины');
INSERT INTO main_category VALUES (95, 30, 'Промывки и промывочное масло');
INSERT INTO main_category VALUES (96, 30, 'Тормозные жидкости');
INSERT INTO main_category VALUES (97, 30, 'Антикоры');
INSERT INTO main_category VALUES (98, 30, 'Смазки');
INSERT INTO main_category VALUES (99, 32, 'Мотоциклы');
INSERT INTO main_category VALUES (100, 32, 'Снегоходы');
INSERT INTO main_category VALUES (101, 32, 'Мотороллеры');
INSERT INTO main_category VALUES (102, 33, 'Седельные тягачи');
INSERT INTO main_category VALUES (103, 33, 'Самосвалы');
INSERT INTO main_category VALUES (104, 33, 'Полуприцепы');
INSERT INTO main_category VALUES (105, 33, 'Лесовозы');
INSERT INTO main_category VALUES (106, 33, 'Бортовые');
INSERT INTO main_category VALUES (107, 33, 'Прицепы');
INSERT INTO main_category VALUES (108, 33, 'Шасси');
INSERT INTO main_category VALUES (109, 33, 'Фургоны');
INSERT INTO main_category VALUES (110, 34, 'Автокраны');
INSERT INTO main_category VALUES (111, 34, 'Экскаваторы и бульдозеры');
INSERT INTO main_category VALUES (112, 34, 'Коммунальная техника');
INSERT INTO main_category VALUES (113, 34, 'Погрузчики');
INSERT INTO main_category VALUES (114, 37, 'Телевизоры и мониторы');
INSERT INTO main_category VALUES (115, 37, 'Видеомагнитофоны');
INSERT INTO main_category VALUES (116, 37, 'DVD-плееры');
INSERT INTO main_category VALUES (117, 9, 'Лекарственные препараты');
INSERT INTO main_category VALUES (118, 9, 'Лечебная одежда и обувь');
INSERT INTO main_category VALUES (119, 9, 'Медицинские материалы');
INSERT INTO main_category VALUES (120, 9, 'Оптика');
INSERT INTO main_category VALUES (121, 9, 'Контрацептивы');
INSERT INTO main_category VALUES (122, 9, 'Медицинские приборы и изделия');
INSERT INTO main_category VALUES (123, 9, 'Диагностические тесты');
INSERT INTO main_category VALUES (124, 9, 'Беременной и кормящей женщине');
INSERT INTO main_category VALUES (125, 120, 'Контактные линзы');
INSERT INTO main_category VALUES (126, 120, 'Аксессуары');
INSERT INTO main_category VALUES (127, 120, 'Cолнцезащитные очки');
INSERT INTO main_category VALUES (128, 7, 'Для дома');
INSERT INTO main_category VALUES (129, 7, 'Для кухни');
INSERT INTO main_category VALUES (130, 7, 'Климатическое оборудование');
INSERT INTO main_category VALUES (131, 7, 'Индивидуальный уход');
INSERT INTO main_category VALUES (132, 128, 'Пылесосы');
INSERT INTO main_category VALUES (133, 128, 'Утюги');
INSERT INTO main_category VALUES (134, 128, 'Швейные и вязальные машинки');
INSERT INTO main_category VALUES (135, 128, 'Сушильные автоматы');
INSERT INTO main_category VALUES (136, 128, 'Фонари');
INSERT INTO main_category VALUES (137, 128, 'Стиральные машины');
INSERT INTO main_category VALUES (138, 128, 'Аксессуары для стиральных машин');
INSERT INTO main_category VALUES (139, 128, 'Аксессуары для пылесосов');
INSERT INTO main_category VALUES (140, 128, 'Системы Умный дом');
INSERT INTO main_category VALUES (141, 134, 'Аксессуары');
INSERT INTO main_category VALUES (142, 134, 'Оверлоки');
INSERT INTO main_category VALUES (143, 134, 'Вязальные машины');
INSERT INTO main_category VALUES (144, 134, 'Швейные машинки');
INSERT INTO main_category VALUES (145, 134, 'Вышивальные машинки');
INSERT INTO main_category VALUES (146, 129, 'Духовки');
INSERT INTO main_category VALUES (147, 129, 'Посудомоечные машины');
INSERT INTO main_category VALUES (148, 129, 'Фритюрницы');
INSERT INTO main_category VALUES (149, 129, 'Кофеварки');
INSERT INTO main_category VALUES (150, 129, 'Тостеры, ростеры');
INSERT INTO main_category VALUES (151, 129, 'Микроволновые печи');
INSERT INTO main_category VALUES (152, 129, 'Соковыжималки');
INSERT INTO main_category VALUES (153, 129, 'Встраиваемые рабочие поверхности');
INSERT INTO main_category VALUES (154, 129, 'Фильтры для очистки воды');
INSERT INTO main_category VALUES (155, 129, 'Весы');
INSERT INTO main_category VALUES (156, 129, 'Электроножи');
INSERT INTO main_category VALUES (157, 129, 'Хлебопечки');
INSERT INTO main_category VALUES (158, 129, 'Пароварки');
INSERT INTO main_category VALUES (159, 129, 'Другое оборудование');
INSERT INTO main_category VALUES (160, 129, 'Вытяжки');
INSERT INTO main_category VALUES (161, 129, 'Электрочайники');
INSERT INTO main_category VALUES (162, 129, 'Мясорубки');
INSERT INTO main_category VALUES (163, 129, 'Миксеры');
INSERT INTO main_category VALUES (164, 129, 'Холодильники');
INSERT INTO main_category VALUES (165, 129, 'Кофемолки');
INSERT INTO main_category VALUES (166, 129, 'Кухонные комбайны');
INSERT INTO main_category VALUES (167, 129, 'Плиты');
INSERT INTO main_category VALUES (168, 129, 'Фильтры для техники');
INSERT INTO main_category VALUES (169, 129, 'Блинницы');
INSERT INTO main_category VALUES (170, 129, 'Яйцеварки');
INSERT INTO main_category VALUES (171, 129, 'Йогуртницы');
INSERT INTO main_category VALUES (172, 129, 'Блендеры');
INSERT INTO main_category VALUES (173, 131, 'Вентиляторы');
INSERT INTO main_category VALUES (174, 131, 'Обогреватели');
INSERT INTO main_category VALUES (175, 131, 'Очистители / увлажнители воздуха');
INSERT INTO main_category VALUES (176, 131, 'Осушители воздуха');
INSERT INTO main_category VALUES (177, 131, 'Ионизаторы');
INSERT INTO main_category VALUES (178, 131, 'Тепловые завесы');
INSERT INTO main_category VALUES (179, 131, 'Водонагреватели');
INSERT INTO main_category VALUES (180, 131, 'Кондиционеры');
INSERT INTO main_category VALUES (181, 131, 'Метеостанции');
INSERT INTO main_category VALUES (182, 131, 'Комплектующие для кондиционеров');
INSERT INTO main_category VALUES (183, 131, 'Аксессуары для климатического оборудования');
INSERT INTO main_category VALUES (184, 130, 'Фены');
INSERT INTO main_category VALUES (185, 130, 'Эпиляторы');
INSERT INTO main_category VALUES (186, 130, 'Весы');
INSERT INTO main_category VALUES (187, 130, 'Щипцы для завивки');
INSERT INTO main_category VALUES (188, 130, 'Электробритвы');
INSERT INTO main_category VALUES (189, 130, 'Машинки для стрижки');
INSERT INTO main_category VALUES (190, 130, 'Электрические зубные щетки');
INSERT INTO main_category VALUES (191, 10, 'Текстиль');
INSERT INTO main_category VALUES (192, 10, 'Мебель');
INSERT INTO main_category VALUES (193, 10, 'Бытовая химия');
INSERT INTO main_category VALUES (194, 10, 'Кухонные принадлежности');
INSERT INTO main_category VALUES (195, 10, 'Хозяйственный инвентарь');
INSERT INTO main_category VALUES (196, 10, 'Светильники');
INSERT INTO main_category VALUES (197, 10, 'Интерьер');
INSERT INTO main_category VALUES (198, 10, 'Сад, огород');
INSERT INTO main_category VALUES (199, 10, 'Аксессуары для ванной и туалета');
INSERT INTO main_category VALUES (200, 10, 'Биотуалет');
INSERT INTO main_category VALUES (201, 10, 'Рукоделие');
INSERT INTO main_category VALUES (202, 10, 'Звонки');
INSERT INTO main_category VALUES (203, 10, 'Электроудлинители и переходники');
INSERT INTO main_category VALUES (204, 191, 'Постельное белье');
INSERT INTO main_category VALUES (205, 191, 'Полотенца');
INSERT INTO main_category VALUES (206, 191, 'Шторы');
INSERT INTO main_category VALUES (207, 192, 'Стулья');
INSERT INTO main_category VALUES (208, 192, 'Письменные столы');
INSERT INTO main_category VALUES (209, 192, 'Шкафы');
INSERT INTO main_category VALUES (210, 192, 'Мебель для кухни');
INSERT INTO main_category VALUES (211, 192, 'Стенки');
INSERT INTO main_category VALUES (212, 192, 'Прихожие');
INSERT INTO main_category VALUES (213, 192, 'Мягкая мебель');
INSERT INTO main_category VALUES (214, 192, 'Детская мебель');
INSERT INTO main_category VALUES (215, 192, 'Спальни');
INSERT INTO main_category VALUES (216, 192, 'Мебель для ванных комнат');
INSERT INTO main_category VALUES (217, 192, 'Гостиные');
INSERT INTO main_category VALUES (218, 192, 'Садовая мебель');
INSERT INTO main_category VALUES (219, 193, 'Моющие средства');
INSERT INTO main_category VALUES (220, 193, 'Чистящие средства');
INSERT INTO main_category VALUES (221, 193, 'Стиральный порошок');
INSERT INTO main_category VALUES (222, 193, 'Освежители');
INSERT INTO main_category VALUES (223, 193, 'Инсектициды');
INSERT INTO main_category VALUES (224, 194, 'Столовые приборы');
INSERT INTO main_category VALUES (225, 194, 'Чайники');
INSERT INTO main_category VALUES (226, 194, 'Кастрюли');
INSERT INTO main_category VALUES (227, 194, 'Сковородки');
INSERT INTO main_category VALUES (228, 194, 'Наборы');
INSERT INTO main_category VALUES (229, 194, 'Кухонный инвентарь');
INSERT INTO main_category VALUES (230, 194, 'Термосы');
INSERT INTO main_category VALUES (231, 194, 'Турки, кофемолки');
INSERT INTO main_category VALUES (232, 194, 'Ножи кухонные');
INSERT INTO main_category VALUES (233, 194, 'Посуда');
INSERT INTO main_category VALUES (234, 196, 'Бра');
INSERT INTO main_category VALUES (235, 196, 'Люстры');
INSERT INTO main_category VALUES (236, 196, 'Настольные лампы');
INSERT INTO main_category VALUES (237, 196, 'Ночники');
INSERT INTO main_category VALUES (238, 196, 'Лампочки');
INSERT INTO main_category VALUES (239, 197, 'Карнизы');
INSERT INTO main_category VALUES (240, 197, 'Зеркала и стекла');
INSERT INTO main_category VALUES (241, 197, 'Жалюзи');
INSERT INTO main_category VALUES (242, 197, 'Часы настенные');
INSERT INTO main_category VALUES (243, 197, 'Часы настольные');
INSERT INTO main_category VALUES (244, 197, 'Напольные часы');
INSERT INTO main_category VALUES (245, 197, 'Каминные часы');
INSERT INTO main_category VALUES (246, 197, 'Элементы интерьера');
INSERT INTO main_category VALUES (247, 197, 'Декоративные фонтаны');
INSERT INTO main_category VALUES (248, 198, 'Газонокосилки');
INSERT INTO main_category VALUES (249, 198, 'Оснастка к садовой технике');
INSERT INTO main_category VALUES (250, 198, 'Мотоблоки');
INSERT INTO main_category VALUES (251, 198, 'Минитракторы');
INSERT INTO main_category VALUES (252, 198, 'Культиваторы');
INSERT INTO main_category VALUES (253, 198, 'Снегоуборщики');
INSERT INTO main_category VALUES (254, 198, 'Насосы и помпы');
INSERT INTO main_category VALUES (255, 198, 'Садовый инвентарь');
INSERT INTO main_category VALUES (256, 198, 'Садовый декор');
INSERT INTO main_category VALUES (257, 198, 'Аксессуары для сада и огорода');
INSERT INTO main_category VALUES (258, 198, 'Вертикуттеры');
INSERT INTO main_category VALUES (259, 198, 'Фонтаны и пруды');
INSERT INTO main_category VALUES (260, 11, 'Одежда');
INSERT INTO main_category VALUES (261, 11, 'Игрушки');
INSERT INTO main_category VALUES (262, 11, 'Для самых маленьких');
INSERT INTO main_category VALUES (263, 11, 'Для школы');
INSERT INTO main_category VALUES (264, 261, 'Игрушки для мальчиков');
INSERT INTO main_category VALUES (265, 261, 'Игрушки для девочек');
INSERT INTO main_category VALUES (266, 261, 'Развивающие игрушки');
INSERT INTO main_category VALUES (267, 261, 'Головоломки, пазлы');
INSERT INTO main_category VALUES (268, 261, 'Конструкторы');
INSERT INTO main_category VALUES (269, 261, 'Активные игры');
INSERT INTO main_category VALUES (270, 261, 'Мягкая игрушка');
INSERT INTO main_category VALUES (271, 261, 'Электронные игрушки');
INSERT INTO main_category VALUES (272, 261, 'Велосипеды, автомобили, самокаты');
INSERT INTO main_category VALUES (273, 261, 'Интерактивные игрушки');
INSERT INTO main_category VALUES (274, 262, 'Коляски');
INSERT INTO main_category VALUES (275, 262, 'Бутылочки, пустышки, соски');
INSERT INTO main_category VALUES (276, 262, 'Пеленки, ползунки');
INSERT INTO main_category VALUES (277, 262, 'Памперсы');
INSERT INTO main_category VALUES (278, 262, 'Автокресла детские');
INSERT INTO main_category VALUES (279, 12, 'Билеты');
INSERT INTO main_category VALUES (280, 279, 'Театр');
INSERT INTO main_category VALUES (281, 279, 'Цирк');
INSERT INTO main_category VALUES (282, 279, 'Концерт');
INSERT INTO main_category VALUES (283, 279, 'Шоу');
INSERT INTO main_category VALUES (284, 279, 'Кино');
INSERT INTO main_category VALUES (285, 279, 'Спорт');
INSERT INTO main_category VALUES (286, 279, 'Мюзикл');
INSERT INTO main_category VALUES (287, 13, 'Растения');
INSERT INTO main_category VALUES (288, 13, 'Животные');
INSERT INTO main_category VALUES (289, 288, 'Домашние животные');
INSERT INTO main_category VALUES (290, 288, 'Предметы обихода для животных');
INSERT INTO main_category VALUES (291, 14, 'Журналы и газеты');
INSERT INTO main_category VALUES (292, 14, 'Художественная литература');
INSERT INTO main_category VALUES (293, 14, 'Компьютеры и интернет');
INSERT INTO main_category VALUES (294, 14, 'Литература на иностранных языках');
INSERT INTO main_category VALUES (295, 14, 'Бизнес и экономика');
INSERT INTO main_category VALUES (296, 14, 'Юридическая литература');
INSERT INTO main_category VALUES (297, 14, 'Искусство и культура');
INSERT INTO main_category VALUES (298, 14, 'Детская литература');
INSERT INTO main_category VALUES (299, 14, 'Дом, быт, семья, досуг');
INSERT INTO main_category VALUES (300, 14, 'Словари, справочники, энциклопедии');
INSERT INTO main_category VALUES (301, 14, 'Техническая литература');
INSERT INTO main_category VALUES (302, 14, 'Медицина');
INSERT INTO main_category VALUES (303, 14, 'Наука и образование');
INSERT INTO main_category VALUES (304, 14, 'Эзотерика');
INSERT INTO main_category VALUES (305, 14, 'Открытки');
INSERT INTO main_category VALUES (306, 14, 'Календари');
INSERT INTO main_category VALUES (307, 14, 'Постеры');
INSERT INTO main_category VALUES (308, 14, 'Аудиокниги');
INSERT INTO main_category VALUES (309, 291, 'Авто, Мото');
INSERT INTO main_category VALUES (310, 291, 'Компьютерная техника и ПО');
INSERT INTO main_category VALUES (311, 291, 'Музыка и кино');
INSERT INTO main_category VALUES (312, 291, 'Спорт, туризм, отдых');
INSERT INTO main_category VALUES (313, 291, 'Журналы для молодежи');
INSERT INTO main_category VALUES (314, 292, 'Поэзия');
INSERT INTO main_category VALUES (315, 292, 'Зарубежная проза');
INSERT INTO main_category VALUES (316, 292, 'Детективы, боевики, триллеры');
INSERT INTO main_category VALUES (317, 292, 'Юмор и сатира');
INSERT INTO main_category VALUES (318, 292, 'Сентиментальный роман');
INSERT INTO main_category VALUES (319, 292, 'Фэнтази');
INSERT INTO main_category VALUES (320, 292, 'Публицистика');
INSERT INTO main_category VALUES (321, 292, 'Исторический роман, приключения');
INSERT INTO main_category VALUES (322, 292, 'Отечественная проза');
INSERT INTO main_category VALUES (323, 292, 'Биографии, мемуары, личности');
INSERT INTO main_category VALUES (324, 292, 'Классическая литература');
INSERT INTO main_category VALUES (325, 292, 'Фантастика');
INSERT INTO main_category VALUES (326, 292, 'Мифы, эпос, сказания');
INSERT INTO main_category VALUES (327, 292, 'Античная литература');
INSERT INTO main_category VALUES (328, 292, 'Разное');
INSERT INTO main_category VALUES (329, 293, 'Языки программирования');
INSERT INTO main_category VALUES (330, 293, 'Базы данных');
INSERT INTO main_category VALUES (331, 293, 'Аппаратное обеспечение');
INSERT INTO main_category VALUES (332, 293, 'Графика, дизайн, CAD');
INSERT INTO main_category VALUES (333, 293, 'Прикладные программные пакеты');
INSERT INTO main_category VALUES (334, 293, 'Программирование в интернет');
INSERT INTO main_category VALUES (335, 293, 'Литература для начинающих');
INSERT INTO main_category VALUES (336, 293, 'Игры');
INSERT INTO main_category VALUES (337, 293, 'Интернет и локальные сети');
INSERT INTO main_category VALUES (338, 293, 'Операционные системы');
INSERT INTO main_category VALUES (339, 293, 'Программы для офиса');
INSERT INTO main_category VALUES (340, 293, 'Разное');
INSERT INTO main_category VALUES (341, 295, 'Аудит');
INSERT INTO main_category VALUES (342, 295, 'Бухгалтерский учет');
INSERT INTO main_category VALUES (343, 295, 'Делопроизводство');
INSERT INTO main_category VALUES (344, 295, 'Менеджмент');
INSERT INTO main_category VALUES (345, 295, 'Недвижимость');
INSERT INTO main_category VALUES (346, 295, 'Статистика');
INSERT INTO main_category VALUES (347, 295, 'Финансы');
INSERT INTO main_category VALUES (348, 295, 'Экономика');
INSERT INTO main_category VALUES (349, 295, 'Банковское дело');
INSERT INTO main_category VALUES (350, 295, 'Валютные операции');
INSERT INTO main_category VALUES (351, 295, 'Маркетинг, реклама');
INSERT INTO main_category VALUES (352, 295, 'Налогообложение');
INSERT INTO main_category VALUES (353, 295, 'Работа');
INSERT INTO main_category VALUES (354, 295, 'Страховое дело');
INSERT INTO main_category VALUES (355, 295, 'Ценные бумаги');
INSERT INTO main_category VALUES (356, 295, 'Таможенное дело');
INSERT INTO main_category VALUES (357, 295, 'Разное');
INSERT INTO main_category VALUES (358, 295, 'Управление персоналом');
INSERT INTO main_category VALUES (359, 296, 'Кодексы и комментарии');
INSERT INTO main_category VALUES (360, 296, 'Гражданское право');
INSERT INTO main_category VALUES (361, 296, 'Нормативные акты и документы');
INSERT INTO main_category VALUES (362, 296, 'Административное право');
INSERT INTO main_category VALUES (363, 296, 'Жилищное, семейное право');
INSERT INTO main_category VALUES (364, 296, 'Международное право');
INSERT INTO main_category VALUES (365, 296, 'Уголовное право');
INSERT INTO main_category VALUES (366, 296, 'Государственное право');
INSERT INTO main_category VALUES (367, 296, 'Разное');
INSERT INTO main_category VALUES (368, 297, 'Архитектура и зодчество');
INSERT INTO main_category VALUES (369, 297, 'Музеи и коллекции');
INSERT INTO main_category VALUES (370, 297, 'Театр, кино, телевидение');
INSERT INTO main_category VALUES (371, 297, 'Творческие личности');
INSERT INTO main_category VALUES (372, 297, 'Изобразительное искусство');
INSERT INTO main_category VALUES (373, 297, 'Музыка, ноты');
INSERT INTO main_category VALUES (374, 297, 'Антикварные книги, редкие книги');
INSERT INTO main_category VALUES (375, 297, 'Разное');
INSERT INTO main_category VALUES (376, 297, 'Фотоискусство');
INSERT INTO main_category VALUES (377, 297, 'Альбомы');
INSERT INTO main_category VALUES (378, 298, 'Для самых маленьких');
INSERT INTO main_category VALUES (379, 298, 'Детские энциклопедии');
INSERT INTO main_category VALUES (380, 298, 'Полезные советы');
INSERT INTO main_category VALUES (381, 298, 'Раскраски, игры, загадки');
INSERT INTO main_category VALUES (382, 298, 'Для дошкольников и младших классов');
INSERT INTO main_category VALUES (383, 298, 'Иностранные языки для детей');
INSERT INTO main_category VALUES (384, 298, 'Разное');
INSERT INTO main_category VALUES (385, 299, 'Домашний мастер');
INSERT INTO main_category VALUES (386, 299, 'Сад, огород');
INSERT INTO main_category VALUES (387, 299, 'Интерьер, дизайн');
INSERT INTO main_category VALUES (388, 299, 'Комнатные растения');
INSERT INTO main_category VALUES (389, 299, 'Мода');
INSERT INTO main_category VALUES (390, 299, 'Рукоделие');
INSERT INTO main_category VALUES (391, 299, 'Кулинария');
INSERT INTO main_category VALUES (392, 299, 'Игры и развлечения');
INSERT INTO main_category VALUES (393, 299, 'Косметика и парфюмерия');
INSERT INTO main_category VALUES (394, 299, 'Животные');
INSERT INTO main_category VALUES (395, 299, 'Ребенок и уход за ним');
INSERT INTO main_category VALUES (396, 299, 'Спорт');
INSERT INTO main_category VALUES (397, 299, 'Разное');
INSERT INTO main_category VALUES (398, 300, 'Словари');
INSERT INTO main_category VALUES (399, 300, 'Справочные издания');
INSERT INTO main_category VALUES (400, 300, 'Толковые словари');
INSERT INTO main_category VALUES (401, 300, 'Путеводители');
INSERT INTO main_category VALUES (402, 300, 'Энциклопедии');
INSERT INTO main_category VALUES (403, 300, 'Разное');
INSERT INTO main_category VALUES (404, 300, 'Руководства');
INSERT INTO main_category VALUES (405, 301, 'Автомобили');
INSERT INTO main_category VALUES (406, 301, 'Корабли');
INSERT INTO main_category VALUES (407, 301, 'Радиоаппаратура');
INSERT INTO main_category VALUES (408, 301, 'Связь');
INSERT INTO main_category VALUES (409, 301, 'Строительство');
INSERT INTO main_category VALUES (410, 301, 'Производство');
INSERT INTO main_category VALUES (411, 301, 'Техника');
INSERT INTO main_category VALUES (412, 301, 'Разное');
INSERT INTO main_category VALUES (413, 301, 'Нормы и Госты');
INSERT INTO main_category VALUES (414, 302, 'Беременность и уход за ребенком');
INSERT INTO main_category VALUES (415, 302, 'Литература для специалистов');
INSERT INTO main_category VALUES (416, 302, 'Фармакология');
INSERT INTO main_category VALUES (417, 302, 'Правильное питание');
INSERT INTO main_category VALUES (418, 302, 'Народная и нетрадиционная медицина');
INSERT INTO main_category VALUES (419, 302, 'Психология');
INSERT INTO main_category VALUES (420, 302, 'Ветеринария');
INSERT INTO main_category VALUES (421, 302, 'Массаж');
INSERT INTO main_category VALUES (422, 302, 'Разное');
INSERT INTO main_category VALUES (423, 303, 'Учебники для школы');
INSERT INTO main_category VALUES (424, 303, 'География');
INSERT INTO main_category VALUES (425, 303, 'Карты и атласы');
INSERT INTO main_category VALUES (426, 303, 'Учебники для техникумов и вузов');
INSERT INTO main_category VALUES (427, 303, 'Иностранные языки');
INSERT INTO main_category VALUES (428, 303, 'Экология');
INSERT INTO main_category VALUES (429, 303, 'Химия');
INSERT INTO main_category VALUES (430, 303, 'Физика');
INSERT INTO main_category VALUES (431, 303, 'Математика');
INSERT INTO main_category VALUES (432, 303, 'Культурология');
INSERT INTO main_category VALUES (433, 303, 'Политология');
INSERT INTO main_category VALUES (434, 303, 'Русский язык и литература');
INSERT INTO main_category VALUES (435, 303, 'Биология');
INSERT INTO main_category VALUES (436, 303, 'Для самообразования');
INSERT INTO main_category VALUES (437, 303, 'Для дошкольников');
INSERT INTO main_category VALUES (438, 303, 'История');
INSERT INTO main_category VALUES (439, 303, 'Этика, эстетика');
INSERT INTO main_category VALUES (440, 303, 'Философия');
INSERT INTO main_category VALUES (441, 303, 'Социология');
INSERT INTO main_category VALUES (442, 303, 'Логика');
INSERT INTO main_category VALUES (443, 303, 'Педагогика');
INSERT INTO main_category VALUES (444, 303, 'Риторика');
INSERT INTO main_category VALUES (445, 303, 'Разное');
INSERT INTO main_category VALUES (446, 303, 'Религии');
INSERT INTO main_category VALUES (447, 304, 'Восточные боевые искусства');
INSERT INTO main_category VALUES (448, 304, 'Йога');
INSERT INTO main_category VALUES (449, 304, 'Магия, оккультизм, мистика');
INSERT INTO main_category VALUES (450, 304, 'Эзотерика');
INSERT INTO main_category VALUES (451, 304, 'Астрология, гороскопы');
INSERT INTO main_category VALUES (452, 304, 'Парапсихология');
INSERT INTO main_category VALUES (453, 15, 'Косметические средства');
INSERT INTO main_category VALUES (454, 15, 'Парфюмерия женская');
INSERT INTO main_category VALUES (455, 15, 'Парфюмерия мужская');
INSERT INTO main_category VALUES (456, 15, 'Предметы гигиены');
INSERT INTO main_category VALUES (457, 15, 'Бритвенные принадлежности');
INSERT INTO main_category VALUES (458, 15, 'Средства по уходу за волосами');
INSERT INTO main_category VALUES (459, 15, 'Средства по уходу за кожей');
INSERT INTO main_category VALUES (460, 15, 'Солярии');
INSERT INTO main_category VALUES (461, 15, 'Маникюрные принадлежности');
INSERT INTO main_category VALUES (462, 15, 'Миостимуляторы');
INSERT INTO main_category VALUES (463, 15, 'Парикмахерские принадлежности');
INSERT INTO main_category VALUES (464, 15, 'Ароматерапия');
INSERT INTO main_category VALUES (465, 15, 'Одежда для похудения / моделирующая одежда');
INSERT INTO main_category VALUES (466, 453, 'Косметика');
INSERT INTO main_category VALUES (467, 453, 'Средства по уходу за телом');
INSERT INTO main_category VALUES (468, 454, 'Духи');
INSERT INTO main_category VALUES (469, 454, 'Туалетная вода');
INSERT INTO main_category VALUES (470, 454, 'Туалетные духи');
INSERT INTO main_category VALUES (471, 454, 'Дезодоранты');
INSERT INTO main_category VALUES (472, 455, 'Дезодоранты');
INSERT INTO main_category VALUES (473, 455, 'Туалетная вода');
INSERT INTO main_category VALUES (474, 455, 'Одеколоны');
INSERT INTO main_category VALUES (475, 456, 'Бумажные средства гигиены');
INSERT INTO main_category VALUES (476, 456, 'Зубная паста, щетки, порошок, полоскание');
INSERT INTO main_category VALUES (477, 456, 'Средства по уходу за телом');
INSERT INTO main_category VALUES (478, 456, 'Средства для ванной');
INSERT INTO main_category VALUES (479, 457, 'Бритва');
INSERT INTO main_category VALUES (480, 457, 'Пена, гель для бритья');
INSERT INTO main_category VALUES (481, 457, 'Средства после бритья');
INSERT INTO main_category VALUES (482, 457, 'Аксессуары');
INSERT INTO main_category VALUES (483, 458, 'Шампуни');
INSERT INTO main_category VALUES (484, 458, 'Ополаскиватели');
INSERT INTO main_category VALUES (485, 16, 'Видеофильмы');
INSERT INTO main_category VALUES (486, 16, 'Музыка');
INSERT INTO main_category VALUES (487, 16, 'Музыкальные инструменты');
INSERT INTO main_category VALUES (488, 486, 'Музыка для детей');
INSERT INTO main_category VALUES (489, 486, 'Классическая');
INSERT INTO main_category VALUES (490, 486, 'Авторская песня');
INSERT INTO main_category VALUES (491, 486, 'Романсы');
INSERT INTO main_category VALUES (492, 486, 'Фольклор');
INSERT INTO main_category VALUES (493, 486, 'Русский рок');
INSERT INTO main_category VALUES (494, 486, 'Русская поп-музыка');
INSERT INTO main_category VALUES (495, 486, 'Alternative');
INSERT INTO main_category VALUES (496, 486, 'Soundtracks');
INSERT INTO main_category VALUES (497, 486, 'Rеggae');
INSERT INTO main_category VALUES (498, 486, 'Rap');
INSERT INTO main_category VALUES (499, 486, 'Pop');
INSERT INTO main_category VALUES (500, 486, 'Blues');
INSERT INTO main_category VALUES (501, 486, 'Latin');
INSERT INTO main_category VALUES (502, 486, 'Heavy metal');
INSERT INTO main_category VALUES (503, 486, 'Hard rock');
INSERT INTO main_category VALUES (504, 486, 'Jazz');
INSERT INTO main_category VALUES (505, 486, 'Classic rock');
INSERT INTO main_category VALUES (506, 486, 'Другая музыка');
INSERT INTO main_category VALUES (507, 487, 'Акустические гитары');
INSERT INTO main_category VALUES (508, 487, 'Электрогитары');
INSERT INTO main_category VALUES (509, 487, 'Ударные инструменты');
INSERT INTO main_category VALUES (510, 487, 'Духовые инструменты');
INSERT INTO main_category VALUES (511, 487, 'Пианино, фортепияно');
INSERT INTO main_category VALUES (512, 487, 'Синтезаторы');
INSERT INTO main_category VALUES (513, 487, 'Аксессуары');
INSERT INTO main_category VALUES (514, 5, 'Телефоны');
INSERT INTO main_category VALUES (515, 5, 'Сотовые телефоны');
INSERT INTO main_category VALUES (516, 5, 'Карты оплаты');
INSERT INTO main_category VALUES (517, 5, 'АОН');
INSERT INTO main_category VALUES (518, 5, 'Автоответчики');
INSERT INTO main_category VALUES (519, 5, 'Радиотелефоны');
INSERT INTO main_category VALUES (520, 5, 'Блоки питания');
INSERT INTO main_category VALUES (521, 5, 'Аксессуары для сотовых телефонов');
INSERT INTO main_category VALUES (522, 5, 'Тарифные планы');
INSERT INTO main_category VALUES (523, 516, 'Интернет карты');
INSERT INTO main_category VALUES (524, 516, 'Телефонные карты');
INSERT INTO main_category VALUES (525, 516, 'IP-телефония');
INSERT INTO main_category VALUES (526, 521, 'Чехлы');
INSERT INTO main_category VALUES (527, 521, 'Аккумуляторы');
INSERT INTO main_category VALUES (528, 521, 'Антенны');
INSERT INTO main_category VALUES (529, 521, 'Переходники');
INSERT INTO main_category VALUES (530, 521, 'Держатели');
INSERT INTO main_category VALUES (531, 521, 'Зарядные устройства');
INSERT INTO main_category VALUES (532, 521, 'Корпуса и панели');
INSERT INTO main_category VALUES (533, 521, 'Hands Free');
INSERT INTO main_category VALUES (534, 521, 'Аксессуары для ПК');
INSERT INTO main_category VALUES (535, 521, 'Гарнитуры');
INSERT INTO main_category VALUES (536, 521, 'Запасные части');
INSERT INTO main_category VALUES (537, 521, 'Data-кабель');
INSERT INTO main_category VALUES (538, 522, 'Тарифные планы МТС');
INSERT INTO main_category VALUES (539, 522, 'Тарифные планы Мегафон');
INSERT INTO main_category VALUES (540, 8, 'Оргтехника');
INSERT INTO main_category VALUES (541, 8, 'Канцелярские принадлежности');
INSERT INTO main_category VALUES (542, 8, 'Офисная мебель');
INSERT INTO main_category VALUES (543, 8, 'Системы безопасности');
INSERT INTO main_category VALUES (544, 8, 'Пишущие машинки');
INSERT INTO main_category VALUES (545, 8, 'Аксессуары для офиса');
INSERT INTO main_category VALUES (546, 540, 'Оборудование для презентаций');
INSERT INTO main_category VALUES (547, 540, 'Копировальные и многофункциональные устройства');
INSERT INTO main_category VALUES (548, 540, 'Калькуляторы');
INSERT INTO main_category VALUES (549, 540, 'Ламинаторы');
INSERT INTO main_category VALUES (550, 540, 'Переплетные устройства');
INSERT INTO main_category VALUES (551, 540, 'Машинки для уничтожения бумаг');
INSERT INTO main_category VALUES (552, 540, 'Расходные материалы');
INSERT INTO main_category VALUES (553, 540, 'Факсы');
INSERT INTO main_category VALUES (554, 540, 'Мини АТС');
INSERT INTO main_category VALUES (555, 540, 'Системные телефоны');
INSERT INTO main_category VALUES (556, 540, 'Оборудование для АТС');
INSERT INTO main_category VALUES (557, 540, 'Телефонные гарнитуры');
INSERT INTO main_category VALUES (558, 546, 'Мультимедиа проекторы');
INSERT INTO main_category VALUES (559, 546, 'Экраны');
INSERT INTO main_category VALUES (560, 546, 'Доски');
INSERT INTO main_category VALUES (561, 546, 'Слайд-проекторы');
INSERT INTO main_category VALUES (562, 546, 'Оверхед-проекторы');
INSERT INTO main_category VALUES (563, 546, 'Аксессуары для проекторов');
INSERT INTO main_category VALUES (564, 541, 'Карандаши');
INSERT INTO main_category VALUES (565, 541, 'Ручки');
INSERT INTO main_category VALUES (566, 541, 'Маркеры и фломастеры');
INSERT INTO main_category VALUES (567, 541, 'Бумага');
INSERT INTO main_category VALUES (568, 541, 'Тетради');
INSERT INTO main_category VALUES (569, 541, 'Блокноты');
INSERT INTO main_category VALUES (570, 541, 'Папки, файлы, конверты');
INSERT INTO main_category VALUES (571, 541, 'Клей, скотч, штрих');
INSERT INTO main_category VALUES (572, 541, 'Скрепки, кнопки');
INSERT INTO main_category VALUES (573, 541, 'Дыроколы, степлеры');
INSERT INTO main_category VALUES (574, 541, 'Ножницы, ножи');
INSERT INTO main_category VALUES (575, 541, 'Органайзеры');
INSERT INTO main_category VALUES (576, 541, 'Офисные наборы');
INSERT INTO main_category VALUES (577, 541, 'Ежедневники, записные книжки');
INSERT INTO main_category VALUES (578, 541, 'Краски, кисти, мелки');
INSERT INTO main_category VALUES (579, 541, 'Ластики, точилки');
INSERT INTO main_category VALUES (580, 541, 'Аксессуары');
INSERT INTO main_category VALUES (581, 541, 'Инструменты для черчения');
INSERT INTO main_category VALUES (582, 541, 'Бухгалтерские книги, бланки, формы');
INSERT INTO main_category VALUES (583, 541, 'Печати и штампы');
INSERT INTO main_category VALUES (584, 542, 'Столы для компьютеров');
INSERT INTO main_category VALUES (585, 542, 'Столы');
INSERT INTO main_category VALUES (586, 542, 'Шкафы и полки');
INSERT INTO main_category VALUES (587, 542, 'Стулья');
INSERT INTO main_category VALUES (588, 542, 'Кресла');
INSERT INTO main_category VALUES (589, 542, 'Готовые комплекты');
INSERT INTO main_category VALUES (590, 17, 'Женская одежда');
INSERT INTO main_category VALUES (591, 17, 'Часы');
INSERT INTO main_category VALUES (592, 17, 'Мужская одежда');
INSERT INTO main_category VALUES (593, 17, 'Галантерея');
INSERT INTO main_category VALUES (594, 17, 'Сопутствующие товары');
INSERT INTO main_category VALUES (595, 17, 'Спортивная одежда и обувь');
INSERT INTO main_category VALUES (596, 17, 'Ювелирные изделия');
INSERT INTO main_category VALUES (597, 591, 'Часы, будильники');
INSERT INTO main_category VALUES (598, 591, 'Часы наручные, карманные');
INSERT INTO main_category VALUES (599, 598, 'Часы мужские');
INSERT INTO main_category VALUES (600, 598, 'Часы женские');
INSERT INTO main_category VALUES (601, 593, 'Зонты');
INSERT INTO main_category VALUES (602, 593, 'Зажигалки');
INSERT INTO main_category VALUES (603, 593, 'Сумки, чемоданы, кейсы, портфели');
INSERT INTO main_category VALUES (604, 593, 'Галстуки');
INSERT INTO main_category VALUES (605, 593, 'Ремни');
INSERT INTO main_category VALUES (606, 593, 'Бижутерия');
INSERT INTO main_category VALUES (607, 593, 'Кошельки, бумажники, портмоне');
INSERT INTO main_category VALUES (608, 18, 'Цветы');
INSERT INTO main_category VALUES (609, 18, 'Сувениры');
INSERT INTO main_category VALUES (610, 18, 'Новогодние товары');
INSERT INTO main_category VALUES (611, 18, 'Аксессуары');
INSERT INTO main_category VALUES (612, 18, 'Подарочные наборы');
INSERT INTO main_category VALUES (613, 18, 'Подарочные свечи');
INSERT INTO main_category VALUES (614, 18, 'Ручки');
INSERT INTO main_category VALUES (615, 18, 'Ножи');
INSERT INTO main_category VALUES (616, 18, 'Модели');
INSERT INTO main_category VALUES (617, 18, 'Оружие');
INSERT INTO main_category VALUES (618, 18, 'Игры');
INSERT INTO main_category VALUES (619, 18, 'Скульптуры');
INSERT INTO main_category VALUES (620, 18, 'Картины');
INSERT INTO main_category VALUES (621, 608, 'Букеты из живых цветов');
INSERT INTO main_category VALUES (622, 608, 'Композиции из сухих цветов');
INSERT INTO main_category VALUES (623, 608, 'Розы');
INSERT INTO main_category VALUES (624, 608, 'Букеты свадебные');
INSERT INTO main_category VALUES (625, 608, 'Композиции из цветов');
INSERT INTO main_category VALUES (626, 608, 'Композиции для офиса');
INSERT INTO main_category VALUES (627, 608, 'Похоронные');
INSERT INTO main_category VALUES (628, 609, 'Сувениры из дерева');
INSERT INTO main_category VALUES (629, 609, 'Сувениры из металла');
INSERT INTO main_category VALUES (630, 609, 'Сувениры из керамики');
INSERT INTO main_category VALUES (631, 609, 'Сувениры из камня');
INSERT INTO main_category VALUES (632, 609, 'Сувениры из стекла');
INSERT INTO main_category VALUES (633, 609, 'Музыкальные сувениры');
INSERT INTO main_category VALUES (634, 609, 'Бизнес подарки');
INSERT INTO main_category VALUES (635, 609, 'Сувениры из кожи');
INSERT INTO main_category VALUES (636, 609, 'Декоративная посуда');
INSERT INTO main_category VALUES (637, 609, 'Сувениры из фарфора');
INSERT INTO main_category VALUES (638, 610, 'Елки');
INSERT INTO main_category VALUES (639, 19, 'Молочные продукты');
INSERT INTO main_category VALUES (640, 19, 'Бакалея');
INSERT INTO main_category VALUES (641, 19, 'Кондитерские изделия');
INSERT INTO main_category VALUES (642, 19, 'Безалкогольные напитки');
INSERT INTO main_category VALUES (643, 19, 'Спиртные напитки');
INSERT INTO main_category VALUES (644, 19, 'Детское питание');
INSERT INTO main_category VALUES (645, 19, 'Чай, кофе, какао');
INSERT INTO main_category VALUES (646, 19, 'Табак');
INSERT INTO main_category VALUES (647, 19, 'Диетическое и лечебное питание');
INSERT INTO main_category VALUES (648, 640, 'Сахар');
INSERT INTO main_category VALUES (649, 642, 'Квас');
INSERT INTO main_category VALUES (650, 642, 'Соки');
INSERT INTO main_category VALUES (651, 642, 'Минеральная вода');
INSERT INTO main_category VALUES (652, 642, 'Столовая вода, питьевая');
INSERT INTO main_category VALUES (653, 643, 'Водка');
INSERT INTO main_category VALUES (654, 643, 'Коньяк');
INSERT INTO main_category VALUES (655, 643, 'Вермут');
INSERT INTO main_category VALUES (656, 643, 'Пиво');
INSERT INTO main_category VALUES (657, 643, 'Шампанское');
INSERT INTO main_category VALUES (658, 643, 'Ликеры');
INSERT INTO main_category VALUES (659, 643, 'Виски');
INSERT INTO main_category VALUES (660, 643, 'Джин');
INSERT INTO main_category VALUES (661, 643, 'Ром, бренди');
INSERT INTO main_category VALUES (662, 643, 'Другие напитки');
INSERT INTO main_category VALUES (663, 643, 'Вино');
INSERT INTO main_category VALUES (664, 645, 'Чай');
INSERT INTO main_category VALUES (665, 645, 'Кофе молотый');
INSERT INTO main_category VALUES (666, 645, 'Кофе в зернах');
INSERT INTO main_category VALUES (667, 645, 'Какао, шоколад');
INSERT INTO main_category VALUES (668, 646, 'Сигареты');
INSERT INTO main_category VALUES (669, 646, 'Табак');
INSERT INTO main_category VALUES (670, 646, 'Аксессуары');
INSERT INTO main_category VALUES (671, 646, 'Трубки');
INSERT INTO main_category VALUES (672, 646, 'Кальяны');
INSERT INTO main_category VALUES (673, 647, 'Заменители сахара');
INSERT INTO main_category VALUES (674, 20, 'Отдых за рубежом');
INSERT INTO main_category VALUES (675, 20, 'Билеты');
INSERT INTO main_category VALUES (676, 20, 'Отдых и лечение в России и странах СНГ');
INSERT INTO main_category VALUES (677, 674, 'Морские и речные круизы');
INSERT INTO main_category VALUES (678, 674, 'Горнолыжные туры');
INSERT INTO main_category VALUES (679, 674, 'Отдых за границей');
INSERT INTO main_category VALUES (680, 674, 'Экскурсионные туры');
INSERT INTO main_category VALUES (681, 21, 'Спортинвентарь');
INSERT INTO main_category VALUES (682, 21, 'Охота, рыболовство');
INSERT INTO main_category VALUES (683, 21, 'Туризм');
INSERT INTO main_category VALUES (684, 21, 'Лодки, плоты');
INSERT INTO main_category VALUES (685, 21, 'Тренажеры');
INSERT INTO main_category VALUES (686, 21, 'Велосипеды');
INSERT INTO main_category VALUES (687, 21, 'Лыжи');
INSERT INTO main_category VALUES (688, 21, 'Горные лыжи');
INSERT INTO main_category VALUES (689, 21, 'Дартс');
INSERT INTO main_category VALUES (690, 21, 'Коньки');
INSERT INTO main_category VALUES (691, 21, 'Мячи');
INSERT INTO main_category VALUES (692, 21, 'Подводное плавание');
INSERT INTO main_category VALUES (693, 21, 'Сетки');
INSERT INTO main_category VALUES (694, 21, 'Роликовые коньки');
INSERT INTO main_category VALUES (695, 21, 'Бильярд');
INSERT INTO main_category VALUES (696, 21, 'Санки, снегокаты');
INSERT INTO main_category VALUES (697, 21, 'Гири, штанги, гантели');
INSERT INTO main_category VALUES (698, 21, 'Скейтбординг');
INSERT INTO main_category VALUES (699, 21, 'Сноубординг');
INSERT INTO main_category VALUES (700, 21, 'Виндсерфинг');
INSERT INTO main_category VALUES (701, 21, 'Большой теннис');
INSERT INTO main_category VALUES (702, 21, 'Настольный теннис');
INSERT INTO main_category VALUES (703, 21, 'Бадминтон');
INSERT INTO main_category VALUES (704, 21, 'Хоккей');
INSERT INTO main_category VALUES (705, 21, 'Бокс');
INSERT INTO main_category VALUES (706, 21, 'Баскетбол');
INSERT INTO main_category VALUES (707, 21, 'Бассейны');
INSERT INTO main_category VALUES (708, 21, 'GPS навигаторы');
INSERT INTO main_category VALUES (709, 21, 'Футбол');
INSERT INTO main_category VALUES (710, 21, 'Гимнастика');
INSERT INTO main_category VALUES (711, 682, 'Ружья');
INSERT INTO main_category VALUES (712, 682, 'Аксессуары');
INSERT INTO main_category VALUES (713, 682, 'Спиннинги, удочки');
INSERT INTO main_category VALUES (714, 682, 'Приманки');
INSERT INTO main_category VALUES (715, 682, 'Мормышки');
INSERT INTO main_category VALUES (716, 682, 'Леска');
INSERT INTO main_category VALUES (717, 682, 'Крючки');
INSERT INTO main_category VALUES (718, 682, 'Грузила');
INSERT INTO main_category VALUES (719, 682, 'Катушки');
INSERT INTO main_category VALUES (720, 682, 'Прикормки');
INSERT INTO main_category VALUES (721, 682, 'Подсачеки');
INSERT INTO main_category VALUES (722, 682, 'Эхолоты');
INSERT INTO main_category VALUES (723, 682, 'Экипировка');
INSERT INTO main_category VALUES (724, 682, 'Прицелы');
INSERT INTO main_category VALUES (725, 683, 'Палатки');
INSERT INTO main_category VALUES (726, 683, 'Спальные мешки');
INSERT INTO main_category VALUES (727, 683, 'Рюкзаки');
INSERT INTO main_category VALUES (728, 685, 'Велотренажеры');
INSERT INTO main_category VALUES (729, 685, 'Беговые дорожки');
INSERT INTO main_category VALUES (730, 685, 'Силовые тренажеры');
INSERT INTO main_category VALUES (731, 685, 'Другие тренажеры');
INSERT INTO main_category VALUES (732, 685, 'Массажеры');
INSERT INTO main_category VALUES (733, 685, 'Степперы');
INSERT INTO main_category VALUES (734, 685, 'Гребные тренажеры');
INSERT INTO main_category VALUES (735, 685, 'Эллиптический тренажер');
INSERT INTO main_category VALUES (736, 686, 'Велосипеды');
INSERT INTO main_category VALUES (737, 686, 'Велоаксессуары');
INSERT INTO main_category VALUES (738, 687, 'Лыжи');
INSERT INTO main_category VALUES (739, 687, 'Аксессуары для лыж');
INSERT INTO main_category VALUES (740, 688, 'Ботинки');
INSERT INTO main_category VALUES (741, 688, 'Крепления');
INSERT INTO main_category VALUES (742, 688, 'Чехлы, сумки');
INSERT INTO main_category VALUES (743, 688, 'Аксессуары для горных лыж');
INSERT INTO main_category VALUES (744, 688, 'Горные лыжи');
INSERT INTO main_category VALUES (745, 688, 'Палки');
INSERT INTO main_category VALUES (746, 692, 'Ласты');
INSERT INTO main_category VALUES (747, 692, 'Аксессуары для подводного плавания');
INSERT INTO main_category VALUES (748, 692, 'Гидрокостюмы и боты для подводного плавания');
INSERT INTO main_category VALUES (749, 694, 'Роликовые коньки');
INSERT INTO main_category VALUES (750, 695, 'Кий');
INSERT INTO main_category VALUES (751, 695, 'Столы');
INSERT INTO main_category VALUES (752, 695, 'Шары');
INSERT INTO main_category VALUES (753, 698, 'Скейтборды');
INSERT INTO main_category VALUES (754, 699, 'Сноуборды');
INSERT INTO main_category VALUES (755, 699, 'Аксессуары для сноубордов');
INSERT INTO main_category VALUES (756, 699, 'Крепления');
INSERT INTO main_category VALUES (757, 699, 'Ботинки');
INSERT INTO main_category VALUES (758, 700, 'Доски');
INSERT INTO main_category VALUES (759, 700, 'Аксессуары для виндсерфинга');
INSERT INTO main_category VALUES (760, 701, 'Ракетки для большого тенниса');
INSERT INTO main_category VALUES (761, 702, 'Ракетки');
INSERT INTO main_category VALUES (762, 702, 'Сетки');
INSERT INTO main_category VALUES (763, 702, 'Аксессуары');
INSERT INTO main_category VALUES (764, 702, 'Столы');
INSERT INTO main_category VALUES (765, 703, 'Ракетки для бадминтона');
INSERT INTO main_category VALUES (766, 22, 'Лакокрасочные материалы');
INSERT INTO main_category VALUES (767, 22, 'Сантехника');
INSERT INTO main_category VALUES (768, 22, 'Фурнитура');
INSERT INTO main_category VALUES (769, 22, 'Ручной инструмент');
INSERT INTO main_category VALUES (770, 22, 'Облицовочные и отделочные материалы');
INSERT INTO main_category VALUES (771, 22, 'Элементы крепежа');
INSERT INTO main_category VALUES (772, 22, 'Электроинструменты');
INSERT INTO main_category VALUES (773, 22, 'Трубы');
INSERT INTO main_category VALUES (774, 22, 'Кровельные и гидроизоляционные материалы');
INSERT INTO main_category VALUES (775, 22, 'Изделия');
INSERT INTO main_category VALUES (776, 22, 'Пиломатериалы');
INSERT INTO main_category VALUES (777, 22, 'Электрика');
INSERT INTO main_category VALUES (778, 22, 'Вентиляция и отопление');
INSERT INTO main_category VALUES (779, 22, 'Стекло, стеклоизделия');
INSERT INTO main_category VALUES (780, 22, 'Материалы');
INSERT INTO main_category VALUES (781, 22, 'Тепло- и шумоизоляционные материалы');
INSERT INTO main_category VALUES (782, 22, 'Измерительный инструмент');
INSERT INTO main_category VALUES (783, 22, 'Готовые конструкции и изделия');
INSERT INTO main_category VALUES (784, 22, 'Окна');
INSERT INTO main_category VALUES (785, 22, 'Двери');
INSERT INTO main_category VALUES (786, 22, 'Сухие смеси, цемент');
INSERT INTO main_category VALUES (787, 22, 'Оснастка к инструментам');
INSERT INTO main_category VALUES (788, 22, 'Бензоинструмент');
INSERT INTO main_category VALUES (789, 22, 'Железобетонные изделия');
INSERT INTO main_category VALUES (790, 22, 'Пневматическое оборудование');
INSERT INTO main_category VALUES (791, 766, 'Краски');
INSERT INTO main_category VALUES (792, 766, 'Лаки');
INSERT INTO main_category VALUES (793, 766, 'Шпаклевки');
INSERT INTO main_category VALUES (794, 766, 'Эмали');
INSERT INTO main_category VALUES (795, 766, 'Растворители');
INSERT INTO main_category VALUES (796, 766, 'Антисептики, морилки, пропитки');
INSERT INTO main_category VALUES (797, 767, 'Смесители, краны');
INSERT INTO main_category VALUES (798, 767, 'Ванны');
INSERT INTO main_category VALUES (799, 767, 'Унитазы');
INSERT INTO main_category VALUES (800, 767, 'Сауны и оборудование');
INSERT INTO main_category VALUES (801, 767, 'Раковины, умывальники');
INSERT INTO main_category VALUES (802, 767, 'Бассейны');
INSERT INTO main_category VALUES (803, 767, 'Душевые кабины');
INSERT INTO main_category VALUES (804, 767, 'Полотенцосушители');
INSERT INTO main_category VALUES (805, 767, 'Кухонные мойки');
INSERT INTO main_category VALUES (806, 767, 'Материалы для сантехнических работ');
INSERT INTO main_category VALUES (807, 768, 'Замки, щеколды, защелки');
INSERT INTO main_category VALUES (808, 768, 'Ручки дверные');
INSERT INTO main_category VALUES (809, 769, 'Ключи');
INSERT INTO main_category VALUES (810, 769, 'Молотки и кувалды');
INSERT INTO main_category VALUES (811, 769, 'Тиски и струбцины');
INSERT INTO main_category VALUES (812, 769, 'Отвертки');
INSERT INTO main_category VALUES (813, 769, 'Ножницы');
INSERT INTO main_category VALUES (814, 769, 'Пилы');
INSERT INTO main_category VALUES (815, 769, 'Наборы инструментов');
INSERT INTO main_category VALUES (816, 769, 'Напильники и надфили');
INSERT INTO main_category VALUES (817, 769, 'Рубанки');
INSERT INTO main_category VALUES (818, 769, 'Стамески');
INSERT INTO main_category VALUES (819, 769, 'Метчики и плашки');
INSERT INTO main_category VALUES (820, 769, 'Пассатижи');
INSERT INTO main_category VALUES (821, 769, 'Клещи и бокорезы');
INSERT INTO main_category VALUES (822, 769, 'Зубила и керны');
INSERT INTO main_category VALUES (823, 770, 'Обои');
INSERT INTO main_category VALUES (824, 770, 'Керамическая плитка');
INSERT INTO main_category VALUES (825, 770, 'Линолеум');
INSERT INTO main_category VALUES (826, 770, 'Гипсокартон');
INSERT INTO main_category VALUES (827, 770, 'Ламинат');
INSERT INTO main_category VALUES (828, 770, 'Потолки');
INSERT INTO main_category VALUES (829, 770, 'Сайдинг');
INSERT INTO main_category VALUES (830, 770, 'Теплый пол');
INSERT INTO main_category VALUES (831, 770, 'Панели ПВХ и МДФ');
INSERT INTO main_category VALUES (832, 824, 'Напольная плитка');
INSERT INTO main_category VALUES (833, 824, 'Облицовочная плитка');
INSERT INTO main_category VALUES (834, 22, 'Листовой материал');
INSERT INTO main_category VALUES (835, 834, 'Гипсокартон');
INSERT INTO main_category VALUES (836, 834, 'ГВЛ');
INSERT INTO main_category VALUES (837, 772, 'Дрели');
INSERT INTO main_category VALUES (838, 772, 'Перфораторы');
INSERT INTO main_category VALUES (839, 772, 'Ударные гайковерты');
INSERT INTO main_category VALUES (840, 772, 'Шуруповерты');
INSERT INTO main_category VALUES (841, 772, 'Борозделы');
INSERT INTO main_category VALUES (842, 772, 'Пистолеты');
INSERT INTO main_category VALUES (843, 772, 'Ножницы');
INSERT INTO main_category VALUES (844, 772, 'Пилы');
INSERT INTO main_category VALUES (845, 772, 'Краскопульты');
INSERT INTO main_category VALUES (846, 772, 'Рубанки');
INSERT INTO main_category VALUES (847, 772, 'Фрезерные машины');
INSERT INTO main_category VALUES (848, 772, 'Шлифовальные машины');
INSERT INTO main_category VALUES (849, 772, 'Отбойники');
INSERT INTO main_category VALUES (850, 772, 'Насосы');
INSERT INTO main_category VALUES (851, 772, 'Степлеры');
INSERT INTO main_category VALUES (852, 772, 'Лобзики');
INSERT INTO main_category VALUES (853, 774, 'Черепица');
INSERT INTO main_category VALUES (854, 774, 'Гидроизоляционные материалы');
INSERT INTO main_category VALUES (855, 774, 'Металлочерепица');
INSERT INTO main_category VALUES (856, 775, 'Металлический прокат, арматура');
INSERT INTO main_category VALUES (857, 775, 'Стекло, стеклоизделия');
INSERT INTO main_category VALUES (858, 776, 'Плинтус');
INSERT INTO main_category VALUES (859, 777, 'Провода, кабели');
INSERT INTO main_category VALUES (860, 777, 'Выключатели');
INSERT INTO main_category VALUES (861, 777, 'Розетки');
INSERT INTO main_category VALUES (862, 777, 'Трансформаторы');
INSERT INTO main_category VALUES (863, 777, 'Стабилизаторы напряжения');
INSERT INTO main_category VALUES (864, 777, 'Электростанции');
INSERT INTO main_category VALUES (865, 777, 'Источники бесперебойного питания');
INSERT INTO main_category VALUES (866, 777, 'Измерительное оборудование');
INSERT INTO main_category VALUES (867, 778, 'Отопительные системы');
INSERT INTO main_category VALUES (868, 778, 'Вентиляция');
INSERT INTO main_category VALUES (869, 778, 'Камины');
INSERT INTO main_category VALUES (870, 778, 'Элементы систем отопления');
INSERT INTO main_category VALUES (871, 778, 'Радиаторы');
INSERT INTO main_category VALUES (872, 780, 'Герметики');
INSERT INTO main_category VALUES (873, 780, 'Кирпич, бетон');
INSERT INTO main_category VALUES (874, 780, 'Песок ');
INSERT INTO main_category VALUES (875, 780, 'Щебень, гравий');
INSERT INTO main_category VALUES (876, 781, 'Теплоизоляционные материалы');
INSERT INTO main_category VALUES (877, 781, 'Шумоизоляционные материалы ');
INSERT INTO main_category VALUES (878, 783, 'Лестницы');
INSERT INTO main_category VALUES (879, 790, 'Компрессоры');
INSERT INTO main_category VALUES (880, 790, 'Пневмоинструменты');
INSERT INTO main_category VALUES (881, 23, 'Для магазинов');
INSERT INTO main_category VALUES (882, 23, 'Банковское ');
INSERT INTO main_category VALUES (883, 23, 'Строительное');
INSERT INTO main_category VALUES (884, 23, 'Издательское');
INSERT INTO main_category VALUES (885, 23, 'Для производства упаковки и тары');
INSERT INTO main_category VALUES (886, 23, 'Рекламные сувениры');
INSERT INTO main_category VALUES (887, 23, 'Системы охраны и сигнализации');
INSERT INTO main_category VALUES (888, 23, 'Полиграфическое');
INSERT INTO main_category VALUES (889, 23, 'Швейное производство');
INSERT INTO main_category VALUES (890, 23, 'Производственно-техническое оборудование');
INSERT INTO main_category VALUES (891, 23, 'Чистящая и моющая техника');
INSERT INTO main_category VALUES (892, 23, 'Пищевая промышленность');
INSERT INTO main_category VALUES (893, 23, 'Грузоподъемное оборудование');
INSERT INTO main_category VALUES (894, 23, 'Станки');
INSERT INTO main_category VALUES (895, 23, 'Для производства и тиражирования CD и DVD дисков');
INSERT INTO main_category VALUES (896, 881, 'Весы');
INSERT INTO main_category VALUES (897, 881, 'Холодильное оборудование');
INSERT INTO main_category VALUES (898, 881, 'Кассовые аппараты');
INSERT INTO main_category VALUES (899, 881, 'Этикет пистолеты');
INSERT INTO main_category VALUES (900, 881, 'Сканеры считывания штрих-кода');
INSERT INTO main_category VALUES (901, 881, 'Витрины');
INSERT INTO main_category VALUES (902, 881, 'Принтеры чеков, этикеток, штрих-кода');
INSERT INTO main_category VALUES (903, 882, 'Счетчики купюр');
INSERT INTO main_category VALUES (904, 882, 'Детекторы валют');
INSERT INTO main_category VALUES (905, 882, 'Табло котировки валют');
INSERT INTO main_category VALUES (906, 882, 'Инкассаторское оборудование');
INSERT INTO main_category VALUES (907, 883, 'Сварочное оборудование');
INSERT INTO main_category VALUES (908, 884, 'Контрольно-измерительное оборудование');
INSERT INTO main_category VALUES (909, 884, 'Проявочные машины');
INSERT INTO main_category VALUES (910, 884, 'Устройства широкоформатной печати');
INSERT INTO main_category VALUES (911, 887, 'Системы контроля доступа');
INSERT INTO main_category VALUES (912, 887, 'Сейфы');
INSERT INTO main_category VALUES (913, 887, 'Системы видеонаблюдения');
INSERT INTO main_category VALUES (914, 887, 'Сигнализация');
INSERT INTO main_category VALUES (915, 887, 'Регулировка движения');
INSERT INTO main_category VALUES (916, 887, 'Замки и фурнитура');
INSERT INTO main_category VALUES (917, 887, 'Электропитание');
INSERT INTO main_category VALUES (918, 888, 'Расходные материалы');
INSERT INTO main_category VALUES (919, 891, 'Профессиональные пылесосы');
INSERT INTO main_category VALUES (920, 891, 'Аппараты высокого давления');
INSERT INTO main_category VALUES (921, 891, 'Поломойные и подметальные машины');
INSERT INTO main_category VALUES (922, 891, 'Моечные установки');
INSERT INTO main_category VALUES (923, 891, 'Принадлежности');
INSERT INTO main_category VALUES (924, 891, 'Моющие средства');
INSERT INTO main_category VALUES (925, 895, 'Дубликаторы ');
INSERT INTO main_category VALUES (926, 895, 'DVD-Video оборудование');
INSERT INTO main_category VALUES (927, 895, 'CD/DVD принтеры и ламинаторы');
INSERT INTO main_category VALUES (928, 895, 'Анализаторы качества дисков');
INSERT INTO main_category VALUES (929, 895, 'Устройства хранения и уничтожения дисков');
INSERT INTO main_category VALUES (930, 895, 'Расходные материалы');
INSERT INTO main_category VALUES (931, 6, 'Аудиотехника для дома');
INSERT INTO main_category VALUES (932, 6, 'Видеомагнитофоны');
INSERT INTO main_category VALUES (933, 6, 'Видеокамеры');
INSERT INTO main_category VALUES (934, 6, 'Телевизоры');
INSERT INTO main_category VALUES (935, 6, 'Аксессуары');
INSERT INTO main_category VALUES (936, 6, 'Моноблоки');
INSERT INTO main_category VALUES (937, 6, 'Спутниковое и кабельное телевидение');
INSERT INTO main_category VALUES (938, 6, 'Кассеты и диски');
INSERT INTO main_category VALUES (939, 6, 'Фото');
INSERT INTO main_category VALUES (940, 6, 'DVD-плееры');
INSERT INTO main_category VALUES (941, 6, 'Домашние кинотеатры');
INSERT INTO main_category VALUES (942, 6, 'Плазменные панели');
INSERT INTO main_category VALUES (943, 6, 'Радиостанции');
INSERT INTO main_category VALUES (944, 6, 'Системы MultiRoom');
INSERT INTO main_category VALUES (945, 931, 'Музыкальные центры');
INSERT INTO main_category VALUES (946, 931, 'Радиоприемники');
INSERT INTO main_category VALUES (947, 931, 'MD и CD проигрыватели');
INSERT INTO main_category VALUES (948, 931, 'Наушники');
INSERT INTO main_category VALUES (949, 931, 'MD-плееры');
INSERT INTO main_category VALUES (950, 931, 'MP3-плееры');
INSERT INTO main_category VALUES (951, 931, 'Деки кассетные');
INSERT INTO main_category VALUES (952, 931, 'Тюнеры, ресиверы, эквалайзеры');
INSERT INTO main_category VALUES (953, 931, 'Микрофоны');
INSERT INTO main_category VALUES (954, 931, 'Усилители');
INSERT INTO main_category VALUES (955, 931, 'Магнитолы');
INSERT INTO main_category VALUES (956, 931, 'Акустические системы');
INSERT INTO main_category VALUES (957, 931, 'Плееры кассетные');
INSERT INTO main_category VALUES (958, 931, 'CD-плееры');
INSERT INTO main_category VALUES (959, 931, 'Диктофоны');
INSERT INTO main_category VALUES (960, 931, 'Комплекты акустики');
INSERT INTO main_category VALUES (961, 931, 'Кассеты и диски');
INSERT INTO main_category VALUES (962, 931, 'Проигрыватели виниловых дисков');
INSERT INTO main_category VALUES (963, 931, 'Караоке');
INSERT INTO main_category VALUES (964, 935, 'Батарейки и аккумуляторы');
INSERT INTO main_category VALUES (965, 935, 'Пульты ДУ');
INSERT INTO main_category VALUES (966, 935, 'Подставки');
INSERT INTO main_category VALUES (967, 935, 'Аксессуары для видеокамер');
INSERT INTO main_category VALUES (968, 935, 'Кабели и разъемы');
INSERT INTO main_category VALUES (969, 939, 'Цифровые фотоаппараты');
INSERT INTO main_category VALUES (970, 939, 'Зеркальные фотоаппараты');
INSERT INTO main_category VALUES (971, 939, 'Аксессуары для цифровых фотоаппаратов');
INSERT INTO main_category VALUES (972, 939, 'Альбомы и рамки');
INSERT INTO main_category VALUES (973, 939, 'Оборудование для профессионалов');
INSERT INTO main_category VALUES (974, 939, 'Аксессуары');
INSERT INTO main_category VALUES (975, 939, 'Лабораторное оборудование');
INSERT INTO main_category VALUES (976, 939, 'Объективы и светофильтры');
INSERT INTO main_category VALUES (977, 939, 'Измерительное оборудование');
INSERT INTO main_category VALUES (978, 939, 'Оборудование для подводной съемки');
INSERT INTO main_category VALUES (979, 939, 'Компактные фотоаппараты');
INSERT INTO main_category VALUES (980, 939, 'Сумки, чехлы');
INSERT INTO main_category VALUES (981, 939, 'Фотовспышки и принадлежности к ним');
INSERT INTO main_category VALUES (982, 939, 'Фотоматериалы и химикаты');
INSERT INTO main_category VALUES (983, 939, 'Штативы и моноподы');
INSERT INTO main_category VALUES (984, 939, 'Бинокли');
INSERT INTO main_category VALUES (985, 939, 'Телескопы');
INSERT INTO main_category VALUES (986, 939, 'Микроскопы');
INSERT INTO main_category VALUES (987, 939, 'Приборы ночного видения');
INSERT INTO main_category VALUES (988, 971, 'Насадки на объектив');
INSERT INTO main_category VALUES (989, 971, 'Чехлы, сумки');
INSERT INTO main_category VALUES (990, 971, 'Источники питания');
INSERT INTO main_category VALUES (991, 3, 'Ноутбуки');
INSERT INTO main_category VALUES (992, 3, 'Комплектующие');
INSERT INTO main_category VALUES (993, 3, 'Мониторы');
INSERT INTO main_category VALUES (994, 3, 'Сканеры');
INSERT INTO main_category VALUES (995, 3, 'Принтеры');
INSERT INTO main_category VALUES (996, 3, 'Настольные компьютеры');
INSERT INTO main_category VALUES (997, 3, 'Серверы');
INSERT INTO main_category VALUES (998, 3, 'Компьютеры Macintosh');
INSERT INTO main_category VALUES (999, 3, 'Расходные материалы');
INSERT INTO main_category VALUES (1000, 3, 'Плоттеры');
INSERT INTO main_category VALUES (1001, 3, 'Аксессуары');
INSERT INTO main_category VALUES (1002, 3, 'КПК');
INSERT INTO main_category VALUES (1003, 3, 'Карты памяти');
INSERT INTO main_category VALUES (1004, 3, 'Сетевое оборудование');
INSERT INTO main_category VALUES (1005, 3, 'Манипуляторы и клавиатуры');
INSERT INTO main_category VALUES (1006, 3, 'USB Flash drive');
INSERT INTO main_category VALUES (1007, 3, 'Мультимедиа');
INSERT INTO main_category VALUES (1008, 3, 'Планшеты, дигитайзеры');
INSERT INTO main_category VALUES (1009, 3, 'Игровые приставки');
INSERT INTO main_category VALUES (1010, 3, 'Программное обеспечение');
INSERT INTO main_category VALUES (1011, 3, 'Карманные электронные устройства');
INSERT INTO main_category VALUES (1012, 3, 'Cardreader');
INSERT INTO main_category VALUES (1013, 992, 'Процессоры (CPU)');
INSERT INTO main_category VALUES (1014, 992, 'Звуковые карты');
INSERT INTO main_category VALUES (1015, 992, 'Модемы');
INSERT INTO main_category VALUES (1016, 992, 'Жесткие диски (HDD)');
INSERT INTO main_category VALUES (1017, 992, 'Модули памяти');
INSERT INTO main_category VALUES (1018, 992, 'Контроллеры');
INSERT INTO main_category VALUES (1019, 992, 'USB-устройства');
INSERT INTO main_category VALUES (1020, 992, 'Комплектующие для портативных компьютеров');
INSERT INTO main_category VALUES (1021, 992, 'Материнские платы');
INSERT INTO main_category VALUES (1022, 992, 'Корпуса');
INSERT INTO main_category VALUES (1023, 992, 'Видеокарты');
INSERT INTO main_category VALUES (1024, 992, 'Оптические накопители');
INSERT INTO main_category VALUES (1025, 992, 'Вентиляторы и системы охлаждения');
INSERT INTO main_category VALUES (1026, 992, 'Блоки питания');
INSERT INTO main_category VALUES (1027, 992, 'Накопители FDD, MOD, ZIP, Jazz, стримеры');
INSERT INTO main_category VALUES (1028, 993, 'Мониторы LCD');
INSERT INTO main_category VALUES (1029, 993, 'Мониторы CRT');
INSERT INTO main_category VALUES (1030, 999, 'Картриджи для плоттеров');
INSERT INTO main_category VALUES (1031, 999, 'Картриджи для принтеров');
INSERT INTO main_category VALUES (1032, 999, 'Кассеты с краской и красящей лентой');
INSERT INTO main_category VALUES (1033, 999, 'Тонеры');
INSERT INTO main_category VALUES (1034, 999, 'Чернила и чернильницы');
INSERT INTO main_category VALUES (1035, 999, 'Бумага и пленка');
INSERT INTO main_category VALUES (1036, 999, 'Барабаны и блоки барабанов (drum unit) ');
INSERT INTO main_category VALUES (1037, 999, 'Расходные материалы для кассовых аппаратов');
INSERT INTO main_category VALUES (1038, 999, 'Картриджи для факсов');
INSERT INTO main_category VALUES (1039, 999, 'Дискеты, диски, кассеты');
INSERT INTO main_category VALUES (1040, 1001, 'Аксессуары для принтеров');
INSERT INTO main_category VALUES (1041, 1001, 'Фильтры и стабилизаторы');
INSERT INTO main_category VALUES (1042, 1001, 'Защитные экраны');
INSERT INTO main_category VALUES (1043, 1001, 'Инструменты');
INSERT INTO main_category VALUES (1044, 1001, 'Кабели, разъемы, переходники');
INSERT INTO main_category VALUES (1045, 1001, 'Kоврики и карманы для мышей');
INSERT INTO main_category VALUES (1046, 1001, 'Сумки и чехлы');
INSERT INTO main_category VALUES (1047, 1001, 'Батареи и аккумуляторы');
INSERT INTO main_category VALUES (1048, 1001, 'Чистящие принадлежности');
INSERT INTO main_category VALUES (1049, 1001, 'Кронштейны, держатели и подставки');
INSERT INTO main_category VALUES (1050, 1001, 'Коробки для дисков и дискет');
INSERT INTO main_category VALUES (1051, 1001, 'Источники бесперебойного питания');
INSERT INTO main_category VALUES (1052, 1001, 'Аксессуары для PDA');
INSERT INTO main_category VALUES (1053, 1001, 'Аксессуары для портативных компьютеров');
INSERT INTO main_category VALUES (1054, 1004, 'Маршрутизаторы, коммутаторы, хабы');
INSERT INTO main_category VALUES (1055, 1004, 'Оборудование Wi-Fi и Bluetooth');
INSERT INTO main_category VALUES (1056, 1004, 'Кабели и разъемы');
INSERT INTO main_category VALUES (1057, 1004, 'Мосты');
INSERT INTO main_category VALUES (1058, 1004, 'Мультиплексоры');
INSERT INTO main_category VALUES (1059, 1004, 'Принт-серверы');
INSERT INTO main_category VALUES (1060, 1004, 'Монтажное оборудование');
INSERT INTO main_category VALUES (1061, 1004, 'Сетевые карты и адаптеры');
INSERT INTO main_category VALUES (1062, 1004, 'Трансиверы');
INSERT INTO main_category VALUES (1063, 1004, 'Беспроводное оборудование');
INSERT INTO main_category VALUES (1064, 1004, 'Системы доступа и коммуникационные сервера');
INSERT INTO main_category VALUES (1065, 1004, 'СКС');
INSERT INTO main_category VALUES (1066, 1004, 'Конвертеры интерфейсов и скоростей');
INSERT INTO main_category VALUES (1067, 1005, 'Клавиатуры, мыши, комплекты');
INSERT INTO main_category VALUES (1068, 1005, 'Джойстики');
INSERT INTO main_category VALUES (1069, 1005, 'Разное');
INSERT INTO main_category VALUES (1070, 1007, 'Миди-клавиатуры');
INSERT INTO main_category VALUES (1071, 1007, 'Микрофоны и наушники');
INSERT INTO main_category VALUES (1072, 1007, 'TV и FM тюнеры');
INSERT INTO main_category VALUES (1073, 1007, 'Колонки');
INSERT INTO main_category VALUES (1074, 1007, 'Оборудование для видеоконференций');
INSERT INTO main_category VALUES (1075, 1009, 'Nintendo');
INSERT INTO main_category VALUES (1076, 1009, 'PlayStation');
INSERT INTO main_category VALUES (1077, 1009, 'Игры для приставок');
INSERT INTO main_category VALUES (1078, 1009, 'PlayStation2');
INSERT INTO main_category VALUES (1079, 1009, 'XBox');
INSERT INTO main_category VALUES (1080, 1009, 'Game Boy');
INSERT INTO main_category VALUES (1081, 1009, 'Аксессуары для игровых приставок');
INSERT INTO main_category VALUES (1082, 1077, 'Игры для Game Boy');
INSERT INTO main_category VALUES (1083, 1077, 'Игры для PlayStation');
INSERT INTO main_category VALUES (1084, 1077, 'Игры для XBox');
INSERT INTO main_category VALUES (1085, 1077, 'Игры для PlayStation2');
INSERT INTO main_category VALUES (1086, 1010, 'Офисные программы');
INSERT INTO main_category VALUES (1087, 1010, 'CAD, CAM ');
INSERT INTO main_category VALUES (1088, 1010, 'СУБД');
INSERT INTO main_category VALUES (1089, 1010, 'Утилиты');
INSERT INTO main_category VALUES (1090, 1010, 'Программы для перевода');
INSERT INTO main_category VALUES (1091, 1010, 'Интернет программы');
INSERT INTO main_category VALUES (1092, 1010, 'Мультимедийные и обучающие пакеты');
INSERT INTO main_category VALUES (1093, 1010, 'Сетевое ПО');
INSERT INTO main_category VALUES (1094, 1010, 'Игры');
INSERT INTO main_category VALUES (1095, 1010, 'Верстка и дизайн');
INSERT INTO main_category VALUES (1096, 1010, 'Операционные системы');
INSERT INTO main_category VALUES (1097, 1010, 'Словари и энциклопедии');
INSERT INTO main_category VALUES (1098, 1010, 'Бухгалтерия и финансы');
INSERT INTO main_category VALUES (1099, 1010, 'Программы для организации коммерческой деятельност');
INSERT INTO main_category VALUES (1100, 1010, 'Системы защиты');
INSERT INTO main_category VALUES (1101, 1010, 'Другое ПО');
INSERT INTO main_category VALUES (1102, 1010, 'Программирование');
INSERT INTO main_category VALUES (1103, 1010, 'Программы для карманных ПК');
INSERT INTO main_category VALUES (1104, 1010, 'Антивирусные программы');
INSERT INTO main_category VALUES (1105, 1011, 'Электронные записные книжки');
INSERT INTO main_category VALUES (1106, 1011, 'Словари и переводчики');
INSERT INTO main_category VALUES (1110, 2, 'Авто');
INSERT INTO main_category VALUES (1111, 2, 'Электроника и бытовая техника');
INSERT INTO main_category VALUES (1112, 2, 'Компьютеры');
INSERT INTO main_category VALUES (1113, 2, 'Образование');
INSERT INTO main_category VALUES (1114, 2, 'Домашнее хозяйство');
INSERT INTO main_category VALUES (1115, 2, 'Строительство и ремонт');
INSERT INTO main_category VALUES (1116, 2, 'Фотография и полиграфия');
INSERT INTO main_category VALUES (1117, 2, 'Спорт');
INSERT INTO main_category VALUES (1118, 2, 'Досуг');
INSERT INTO main_category VALUES (1119, 1118, 'Интимные услуги');
INSERT INTO main_category VALUES (1120, 1110, 'Ремонт');
INSERT INTO main_category VALUES (1121, 1110, 'Обучение вождению');
INSERT INTO main_category VALUES (1122, 1110, 'Транспорные услуги');
INSERT INTO main_category VALUES (1123, 1110, 'Перегон');
INSERT INTO main_category VALUES (1124, 1110, 'Автострахование');
INSERT INTO main_category VALUES (1125, 2, 'Реклама и информация');
INSERT INTO main_category VALUES (1126, 1125, 'Печатные СМИ');
INSERT INTO main_category VALUES (1127, 1125, 'Телевидение');
INSERT INTO main_category VALUES (1128, 1125, 'Интернет');
INSERT INTO main_category VALUES (1129, 1112, 'Обучение');
INSERT INTO main_category VALUES (1130, 1112, 'Ремонт и настройка');
INSERT INTO main_category VALUES (1131, 1112, 'Программирование');
INSERT INTO main_category VALUES (1132, 2, 'Интернет');
INSERT INTO main_category VALUES (1133, 1132, 'Обучение работе в Интернет');
INSERT INTO main_category VALUES (1134, 1132, 'Разработка WEB-сайтов');
INSERT INTO main_category VALUES (1135, 1118, 'Дискотеки');
INSERT INTO main_category VALUES (1136, 1118, 'Детские клубы');
INSERT INTO main_category VALUES (1137, 2, 'Здоровье и медицина');
INSERT INTO main_category VALUES (1139, 1117, 'Альпинизм и скалолазание');
INSERT INTO main_category VALUES (1140, 1117, 'Сноубординг');
INSERT INTO main_category VALUES (1141, 1117, 'Горные лыжи');
INSERT INTO main_category VALUES (1142, 1117, 'Пеший туризм');
INSERT INTO main_category VALUES (1143, 1117, 'Пейнтбол');
INSERT INTO main_category VALUES (1144, 1115, 'Внутренняя отделка помещений');
INSERT INTO main_category VALUES (1145, 1115, 'Наружняя отделка зданий');
INSERT INTO main_category VALUES (1146, 1115, 'Строительство');
INSERT INTO main_category VALUES (1147, 1, 'Интернет');
INSERT INTO main_category VALUES (1148, 1147, 'Сайты');
INSERT INTO main_category VALUES (1149, 1147, 'Доменные имена');
INSERT INTO main_category VALUES (1150, 1113, 'Рефераты, курсовые, дипломные работы');
INSERT INTO main_category VALUES (1151, 1113, 'Колледжи');
INSERT INTO main_category VALUES (1152, 1113, 'Школы');
INSERT INTO main_category VALUES (1153, 1113, 'Внешкольная работа');
INSERT INTO main_category VALUES (1154, 1113, 'Репетиторство');
INSERT INTO main_category VALUES (1155, 1154, 'Английский язык');
INSERT INTO main_category VALUES (1156, 1154, 'Немецкий язык');
INSERT INTO main_category VALUES (1157, 1154, 'Физика');
INSERT INTO main_category VALUES (1158, 1154, 'Математика');
INSERT INTO main_category VALUES (1159, 1154, 'Русский язык');
INSERT INTO main_category VALUES (1160, 1154, 'Литература');
INSERT INTO main_category VALUES (1161, 1154, 'История');
INSERT INTO main_category VALUES (1162, 1116, 'Бланки');
INSERT INTO main_category VALUES (1163, 1116, 'Открытки');
INSERT INTO main_category VALUES (1164, 1116, 'Этикетки');
INSERT INTO main_category VALUES (1165, 1116, 'Визитки');
INSERT INTO main_category VALUES (1166, 1116, 'Изготовление рекламных щитов');
INSERT INTO main_category VALUES (1167, 1114, 'Няньки/сиделки');
INSERT INTO main_category VALUES (1168, 1114, 'Прачечная');
INSERT INTO main_category VALUES (1169, 1114, 'Уборка');
INSERT INTO main_category VALUES (1170, 1137, 'Медобследование');
INSERT INTO main_category VALUES (1171, 1137, 'Стоматологические клиники');
INSERT INTO main_category VALUES (1172, 1137, 'Женская консультация');
INSERT INTO main_category VALUES (1173, 1115, 'Сантехнические работы');
INSERT INTO main_category VALUES (1174, 1111, 'Сотовые телефоны');
INSERT INTO main_category VALUES (1175, 1174, 'Ремонт, перепрошивка, разблокировка');
INSERT INTO main_category VALUES (1176, 1174, 'Отслеживание');
INSERT INTO main_category VALUES (1177, 1174, 'Закачка мелодий, игр, картинок');
INSERT INTO main_category VALUES (1178, 1111, 'Бытовая техника');
INSERT INTO main_category VALUES (1179, 1178, 'Ремонт, настройка');
INSERT INTO main_category VALUES (1180, 2, 'Бизнес');
INSERT INTO main_category VALUES (1181, 1180, 'Консультации');
INSERT INTO main_category VALUES (1182, 1180, 'Оформление документов');
INSERT INTO main_category VALUES (1183, 1180, 'Обмен валюты');
INSERT INTO main_category VALUES (1184, 1180, 'Аренда помещений');
INSERT INTO main_category VALUES (1185, 1180, 'Кредитование');
INSERT INTO main_category VALUES (1186, 2, 'Юриспруденция и право');
INSERT INTO main_category VALUES (1187, 1186, 'Юридические консультации');
INSERT INTO main_category VALUES (1188, 1186, 'Адвокаты');
INSERT INTO main_category VALUES (1189, 1117, 'Фитнесс');
INSERT INTO main_category VALUES (1190, 1117, 'Бассейны');
INSERT INTO main_category VALUES (1191, 1117, 'Спортивные базы');
INSERT INTO main_category VALUES (1192, 1113, 'Языковые переводы');
INSERT INTO main_category VALUES (1193, 1192, 'Английский');
INSERT INTO main_category VALUES (1194, 1192, 'Немецкий');
INSERT INTO main_category VALUES (1195, 1192, 'Французский');
INSERT INTO main_category VALUES (1196, 1192, 'Японский');
INSERT INTO main_category VALUES (1197, 1192, 'Китайский');
INSERT INTO main_category VALUES (1198, 1112, 'Прокат/аренда компьютеров');
INSERT INTO main_category VALUES (1199, 1112, 'Настройка компьютеров');
INSERT INTO main_category VALUES (1200, 1112, 'Установка ПО');
INSERT INTO main_category VALUES (1201, 1112, 'Набор текстов');
INSERT INTO main_category VALUES (1202, 1132, 'Поиск в Интернет');
INSERT INTO main_category VALUES (1203, 1112, 'Компьютерные игры');
INSERT INTO main_category VALUES (1204, 1132, 'Доступ в Интернет');
INSERT INTO main_category VALUES (1205, 1132, 'Подключение и настройка Интернет');
INSERT INTO main_category VALUES (1206, 191, 'Пледы');
INSERT INTO main_category VALUES (1207, 191, 'Подушки');
INSERT INTO main_category VALUES (1208, 191, 'Одеяла');
INSERT INTO main_category VALUES (1209, 191, 'Матрацы и наматрасники');
INSERT INTO main_category VALUES (1210, 191, 'Сувенирная продукция');
INSERT INTO main_category VALUES (1211, 191, 'Покрывала');
INSERT INTO main_category VALUES (1212, 191, 'Скатерти');
INSERT INTO main_category VALUES (1213, 262, 'Постельные принадлежности');
INSERT INTO main_category VALUES (1214, 262, 'Комплекты для купания');
INSERT INTO main_category VALUES (1215, 17, 'Женская обувь');
INSERT INTO main_category VALUES (1216, 17, 'Мужская обувь');
INSERT INTO main_category VALUES (1217, 592, 'Халаты');
INSERT INTO main_category VALUES (1218, 592, 'Куртки');
INSERT INTO main_category VALUES (1219, 592, 'Жилеты');
INSERT INTO main_category VALUES (1220, 592, 'Трикотаж');
INSERT INTO main_category VALUES (1221, 592, 'Костюмы');
INSERT INTO main_category VALUES (1222, 590, 'Халаты');
INSERT INTO main_category VALUES (1223, 590, 'Куртки');
INSERT INTO main_category VALUES (1224, 590, 'Жилеты');
INSERT INTO main_category VALUES (1225, 590, 'Трикотаж');
INSERT INTO main_category VALUES (1226, 590, 'Костюмы');
INSERT INTO main_category VALUES (1227, 1216, 'Зимняя мужская обувь');
INSERT INTO main_category VALUES (1228, 1216, 'Летняя мужская обувь');
INSERT INTO main_category VALUES (1229, 1215, 'Летняя женская обувь');
INSERT INTO main_category VALUES (1230, 1215, 'Зимняя женская обувь');
INSERT INTO main_category VALUES (1231, 834, 'ДСП');
INSERT INTO main_category VALUES (1232, 834, 'ДВП');
INSERT INTO main_category VALUES (1233, 834, 'Фанера');
INSERT INTO main_category VALUES (1234, 771, 'Профили');
INSERT INTO main_category VALUES (1235, 771, 'Заклепки');
INSERT INTO main_category VALUES (1236, 771, 'Гвозди');
INSERT INTO main_category VALUES (1237, 771, 'Шурупы');
INSERT INTO main_category VALUES (1238, 771, 'Саморезы');
INSERT INTO main_category VALUES (1239, 771, 'Болты анкерные');
INSERT INTO main_category VALUES (1240, 773, 'Метапол');
INSERT INTO main_category VALUES (1241, 773, 'Стальные');
INSERT INTO main_category VALUES (1242, 773, 'Чугунные');
INSERT INTO main_category VALUES (1243, 773, 'Керамические');
INSERT INTO main_category VALUES (1244, 773, 'Пластик');
INSERT INTO main_category VALUES (1245, 785, 'Деревянные');
INSERT INTO main_category VALUES (1246, 785, 'Пластиковые');
INSERT INTO main_category VALUES (1247, 785, 'Металлические');
INSERT INTO main_category VALUES (1248, 776, 'Доски');
INSERT INTO main_category VALUES (1249, 776, 'Рейки');
INSERT INTO main_category VALUES (1250, 22, 'Кисти и валики');
INSERT INTO main_category VALUES (1251, 1116, 'Фото на документы');
INSERT INTO main_category VALUES (1252, 1116, 'Художественное фото');
INSERT INTO main_category VALUES (1253, 1116, 'Обработка фотографий');
INSERT INTO main_category VALUES (1254, 1116, 'Фотосъемка с выездом фотографа');
INSERT INTO main_category VALUES (1255, 1116, 'Создание портфолио');
INSERT INTO main_category VALUES (1256, 1125, 'Наружная реклама');