# Generated by Django 4.2.7 on 2024-02-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thingimage',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
