# Generated by Django 4.2.7 on 2024-02-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_feedback_user_side_alter_location_city_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thing',
            name='images',
        ),
        migrations.AddField(
            model_name='thing',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.DeleteModel(
            name='ThingImage',
        ),
    ]
