# Generated by Django 4.2.7 on 2024-02-28 17:50

import apps.main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_image_remove_category_parent_id_remove_thing_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='local_url',
            field=models.ImageField(default='', upload_to=apps.main.models.upload_to),
        ),
        migrations.AddField(
            model_name='image',
            name='url_to_upload',
            field=models.CharField(default='', max_length=200),
        ),
    ]
